services:
  garminfilter-api:
    build:
      context: .
      dockerfile: ./src/GarminFilter.Api/Dockerfile
    container_name: garminfilter-api
    ports:
      - "8080:8080"
    volumes:
      - garminfilter-data:/app/data
    environment:
      - DatabasePath=data
      - Origin=http://localhost:3000

volumes:
  garminfilter-data:
